import Layout from "@/components/Layout";
import React, { useState } from "react";
import Head from "next/head";

const Contact = () => {
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [subject, setSubject] = useState('')
  const [message, setMessage] = useState('')
  const [loading, setLoading] = useState(false)

  const handleFormSubmit = (e) => {
    setLoading(true)
    e.preventDefault();
    fetch("https://formsubmit.co/ajax/email", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify({
        name: name,
        message: message,
        email: email,
        subject: subject,
      }),
    })
      .then((response) => response.json())
      .then((data) => {
        console.log(data);
        if (data.success == "true") {
          toast.success("Message sent successfully !");
        } else {
          setLoading(false)
          toast.warn("Oops an error occoured!");
        }
      })
      .catch((error) => {
        console.log(error);
        toast.error("Error: " + error.message)
        setLoading(false)
      });
  }

  return (
    <>
      <Head>
        <title>Cabby | Contact Us</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="sm:my-16 my-32">
          <div className="text-center lg:w-1/2 mx-auto lg:p-0 p-8">
            <p className="text-4xl font-bold my-2">
              Send us a message
            </p>
            <p className="m-0 mb-2 p-0">
              If you have any work from me or any types of queries related
              to our forum you can send us a message now. Its our pleasure
              to help
            </p>
            <form onSubmit={(e) => handleFormSubmit(e)}>
              <div className="mb-3">
                <input
                  required
                  type="text"
                  className="border p-3 w-full"
                  placeholder="Enter your Name"
                  onChange={(e) => setName(e.target.value)}
                />
              </div>
              <div className="mb-4">
                <input
                  required
                  type="email"
                  className="border w-full p-3"
                  placeholder="Enter your Email"
                  onChange={(e) => setEmail(e.target.value)}
                />
              </div>
              <div className="mb-4">
                <input
                  type="text"
                  required
                  className="border p-3 w-full"
                  placeholder="Enter the subject"
                  onChange={(e) => setSubject(e.target.value)}
                />
              </div>

              <textarea
                name=""
                id=""
                cols={30}
                rows={6}
                className="border w-full p-3 mb-3"
                placeholder="Enter your Message"
                required
                onChange={(e) => setMessage(e.target.value)}
              ></textarea>
              <button className="bg-black w-full  px-5 p-3 text-white rounded-md">
                {loading ? "Sending..." : "Send Message"}
              </button>
            </form>
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Contact;