import Layout from "@/components/Layout";
import React, { useState } from "react";
import Head from "next/head";

const Privacy = () => {
  return (
    <>
      <Head>
        <title>Cabby | Privacy Policy</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="sm:my-16 my-32">
          <div className=" lg:w-1/2 mx-auto lg:p-0 p-8">

          </div>
        </div>
      </Layout>
    </>
  );
};

export default Privacy;