import Layout from "@/components/Layout";
import React, { useState } from "react";
import Head from "next/head";

const Terms = () => {
  return (
    <>
      <Head>
        <title>Cabby | Terms and Condition</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="sm:my-16 my-32">
          <div className=" lg:w-1/2 mx-auto lg:p-0 p-8">
            <h1 className='text-3xl my-4'>Terms and Conditions - Cabby Ride-Hailing Service</h1>

            Please read these Terms and Conditions carefully before using the Cabby ride-hailing service. By accessing or using Cabby, you acknowledge and agree to be bound by these terms. If you do not agree with any of the provisions outlined below, please refrain from using Cabby.
            <br /> <br />
            1. User Eligibility: <br />
            a. Cabby is available to individuals who are at least 18 years old. <br />
            b. By using Cabby, you confirm that you have the legal capacity to enter into a binding agreement.
            <br /> <br />

            2. Use of the Service: <br />
            a. Cabby provides a platform that allows users to connect with drivers for ridesharing purposes. <br />
            b. Users must provide accurate and up-to-date information during registration and when requesting a ride. <br />
            c. Users are responsible for maintaining the confidentiality of their account credentials and are liable for any activity that occurs under their account. <br />
            d. Users must not use Cabby for any unlawful or unauthorized purposes.
            <br /> <br />

            3. Safety and Conduct: <br />
            a. Cabby prioritizes the safety of both riders and drivers. Users are expected to treat each other with respect and follow local traffic laws. <br />
            b. Any form of harassment, discrimination, or inappropriate behavior is strictly prohibited. Users found to be engaging in such behavior may be banned from using Cabby. <br />
            c. Users are encouraged to report any safety concerns or incidents to Cabby's customer support team.
            <br /> <br />

            4. Fare Calculation and Payments: <br />
            a. Cabby employs a fare calculation system based on factors such as distance, time, and demand. Fare estimates are provided for transparency, but actual fares may vary. <br />
            b. Users agree to pay the fare displayed on the app at the end of the ride. <br />
            c. Payments can be made through the designated payment methods accepted by Cabby. <br />
            d. Cabby may charge additional fees for services such as cancellation or cleaning.
            <br /> <br />

            5. Limitation of Liability: <br />
            a. Cabby is a platform connecting riders and drivers. We do not guarantee the availability, reliability, or quality of any ride or driver. <br />
            b. Cabby shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from the use or inability to use the service.
            <br /> <br />

            6. Privacy: <br />
            a. Cabby collects and processes personal information in accordance with its Privacy Policy. By using Cabby, you consent to the collection, use, and sharing of your personal information as described in the Privacy Policy.
            <br /> <br />

            7. Modification of Terms: <br />
            a. Cabby reserves the right to modify or update these Terms and Conditions at any time. Users will be notified of any significant changes, and continued use of Cabby after the modifications will constitute acceptance of the updated terms.
            <br /> <br />

            8. Termination: <br />
            a. Cabby may terminate or suspend a user's access to the service at any time without prior notice, for reasons including but not limited to violation of these Terms and Conditions or misuse of the platform.
            <br /> <br />

            9. Governing Law and Dispute Resolution: <br />
            a. These Terms and Conditions shall be governed by and construed in accordance with the laws of the jurisdiction in which Cabby operates. <br />
            b. Any disputes arising from or related to these Terms and Conditions shall be resolved through arbitration or other mutually agreed-upon methods.
            <br /> <br />

            10. Severability: <br />
            a. If any provision of these Terms and Conditions is found to be unenforceable or invalid, the remaining provisions shall remain in full force and effect.
            <br /> <br />

            By using Cabby, you acknowledge that you have read, understood, and agreed to these Terms and Conditions.

            <h1 className="text-3xl my-4">Driver Terms and Conditions - Cabby Ride-Hailing Service</h1>

            Please read these Driver Terms and Conditions carefully before becoming a driver for Cabby. By accessing or using Cabby as a driver, you acknowledge and agree to be bound by these terms. If you do not agree with any of the provisions outlined below, please refrain from becoming a driver for Cabby.
            <br /> <br />

            1. Driver Eligibility: <br />
            a. Drivers must be at least 21 years old. <br />
            b. Drivers must possess a valid driver's license and necessary permits required by local authorities to provide ride-hailing services. <br />
            c. Drivers must have a registered, insured, and roadworthy vehicle that meets Cabby's vehicle requirements.
            <br /> <br />

            2. Driver Responsibilities: <br />
            a. Drivers are responsible for providing safe and reliable transportation services to Cabby riders. <br />
            b. Drivers must maintain a professional and courteous demeanor towards riders and follow all applicable local traffic laws. <br />
            c. Drivers must ensure their vehicles are clean, well-maintained, and suitable for passenger transport. <br />
            d. Drivers must update their availability status accurately on the Cabby app.
            <br /> <br />

            3. Account and Vehicle Information: <br />
            a. Drivers must provide accurate and up-to-date personal information during the registration process. <br />
            b. Drivers must provide the necessary documentation and information related to their vehicle, including valid insurance and registration documents. <br />
            c. Drivers are responsible for updating any changes in their personal or vehicle information promptly.
            <br /> <br />

            4. Safety and Conduct: <br />
            a. Drivers must prioritize the safety and well-being of riders at all times. <br />
            b. Drivers must not engage in any form of harassment, discrimination, or inappropriate behavior towards riders. <br />
            c. Drivers must report any safety concerns or incidents involving riders to Cabby's customer support team immediately.
            <br /> <br />

            5. Fare Calculation and Payments: <br />
            a. Cabby employs a fare calculation system based on factors such as distance, time, and demand. The fare displayed on the app is the amount riders are charged. <br />
            b. Cabby will process payments from riders on behalf of drivers, and drivers will receive their earnings according to the agreed-upon payment terms. <br />
            c. Drivers agree to receive payments via the designated payment methods accepted by Cabby.
            <br /> <br />

            6. Ratings and Reviews: <br />
            a. Cabby allows riders to rate and review drivers based on their experience. <br />
            b. Drivers acknowledge that their ratings and reviews may affect their reputation and future opportunities to provide services through Cabby.
            <br /> <br />

            7. Insurance: <br />
            a. Drivers are responsible for maintaining adequate insurance coverage for their vehicles and complying with all applicable insurance laws and regulations. <br />
            b. Cabby may provide additional insurance coverage for drivers during the provision of rides, subject to the terms and conditions of the insurance policy.
            <br /> <br />

            8. Termination: <br />
            a. Cabby reserves the right to terminate or suspend a driver's access to the service at any time without prior notice, for reasons including but not limited to violation of these Driver Terms and Conditions or failure to meet Cabby's performance standards.
            <br /> <br />

            9. Intellectual Property: <br />
            a. Cabby retains all rights, title, and interest in its brand, logos, and intellectual property. Drivers shall not use Cabby's intellectual property without prior written consent.
            <br /> <br />

            10. Governing Law and Dispute Resolution: <br />
            a. These Driver Terms and Conditions shall be governed by and construed in accordance with the laws of the jurisdiction in which Cabby operates. <br />
            b. Any disputes arising from or related to these Driver Terms and Conditions shall be resolved through arbitration or other mutually agreed-upon methods.
            <br /> <br />

            By becoming a driver for Cabby, you acknowledge that you have read, understood, and agreed to these Driver Terms and Conditions.
          </div>
        </div>
      </Layout>
    </>
  );
};

export default Terms;